// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";

function reportWebVitals(onPerfEntry) {
  var importWebVitals = (import('web-vitals'));
  importWebVitals.then(function (webVitals) {
        Curry._1(webVitals.getCLS, onPerfEntry);
        Curry._1(webVitals.getFID, onPerfEntry);
        Curry._1(webVitals.getFCP, onPerfEntry);
        Curry._1(webVitals.getLCP, onPerfEntry);
        Curry._1(webVitals.getTTFB, onPerfEntry);
        return Promise.resolve(undefined);
      });
  
}

var $$default = reportWebVitals;

export {
  reportWebVitals ,
  $$default ,
  $$default as default,
  
}
/* No side effect */
